### ISSUE TITLE
gw season end?

### ISSUE THREAD

**Issue by eatyourveg** [maphe/e7leaks#5]
events.json

"name": "RTA Season End",
      "start": "2020-11-14 10:00:00Z",
      "url": "https://page.onstove.com/epicseven/global/view/6267503"

url says gw season end, not rta?

**Comment by maphe** [comment]
Ah yeah, thanks, I'll fix later today, the alert is only gonna show up 48h before the date, so I have some time.

Thank for catching it tho 👍

**Comment by maphe** [comment]
Fixed
